export interface FilipinoPersonnel {
  id: string;
  name: string;
  nickname: string;
  role: string;
  department:
    | "MANAGEMENT"
    | "CIVIL"
    | "ELECTRICAL"
    | "SAFETY"
    | "LOGISTICS"
    | "CAMP_SERVICES"
    | "QA_QC"
    | "ENGINEERING"
    | "ADMIN_HR"
    | "MEDICAL"
    | "IT_SYSTEMS";
  skinTone: "LIGHT" | "MEDIUM" | "BRONZE" | "DEEP";
  gender: "MALE" | "FEMALE";
  hardhatColor: string;
  vestColor: string;
  hairStyle: "SHORT" | "POMPADOUR" | "PONYTAIL" | "CHEF_BANDANA" | "BALD";
  facialHair?: "NONE" | "MUSTACHE" | "BEARD" | "GOATEE" | "STUBBLE";
  hasGlasses?: boolean;
  avatarUrl: string;
  licenseNumber: string;
  currentTask: string;
  locationName: string;
  shift: string;
  yearsOfExp: number;
  originProvince: string;
}

export const FILIPINO_PERSONNEL_REGISTRY: Record<string, FilipinoPersonnel> = {
  // ─── 1. MANAGEMENT & LEADERSHIP ───
  "PM_ROMEO_SESE": {
    id: "PM_ROMEO_SESE",
    name: "Engr. Romeo Sese",
    nickname: "PM Romy",
    role: "Resident Project Manager (In-Charge of Whole Tumauini HEPP)",
    department: "MANAGEMENT",
    skinTone: "MEDIUM",
    gender: "MALE",
    hardhatColor: "#FFFFFF",
    vestColor: "#0F766E", // Teal Management Vest
    hairStyle: "SHORT",
    facialHair: "MUSTACHE",
    hasGlasses: true,
    avatarUrl: "/images/personnel/pm_danilo_roxas.jpg",
    licenseNumber: "PRC Civil Eng. #0048291 • APEC Engineer",
    currentTask: "Overall Project Management & Directing Site Operations across Tumauini HEPP",
    locationName: "Project Manager's Office",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 26,
    originProvince: "Pampanga, Philippines",
  },
  "DEPUTY_NATHANIEL_PRINCIPE": {
    id: "DEPUTY_NATHANIEL_PRINCIPE",
    name: "Nathaniel P. Principe",
    nickname: "Deputy Nath",
    role: "Deputy Project Manager",
    department: "MANAGEMENT",
    skinTone: "MEDIUM",
    gender: "MALE",
    hardhatColor: "#FFFFFF",
    vestColor: "#0F766E",
    hairStyle: "SHORT",
    facialHair: "NONE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/deputy_nathaniel_principe.jpg",
    licenseNumber: "PRC Civil Engineer #0051280 • PMP Certified",
    currentTask: "Assisting Project Manager in daily contractor coordination, milestone tracking & field execution",
    locationName: "Deputy Project Manager's Office (Main TEMFACIL Executive Wing)",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 22,
    originProvince: "Isabela, Philippines",
  },

  // ─── 2. TECHNICAL, ENGINEERING & QUALITY ASSURANCE ───
  "ENGR_NOEL_LAVAPIE": {
    id: "ENGR_NOEL_LAVAPIE",
    name: "Engr. Noel G. Lavapie",
    nickname: "Engr. Noel",
    role: "Lead Technical & Project Engineering Head",
    department: "ENGINEERING",
    skinTone: "MEDIUM",
    gender: "MALE",
    hardhatColor: "#FFFFFF",
    vestColor: "#EA580C",
    hairStyle: "SHORT",
    facialHair: "NONE",
    hasGlasses: true,
    avatarUrl: "/images/personnel/engr_noel_lavapie_real.jpg",
    licenseNumber: "PRC Professional Civil Engineer #0038914",
    currentTask: "Reviewing structural shop drawings, methodology statements & supervising technical engineering team",
    locationName: "Main Technical & Project Engineering Office",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 24,
    originProvince: "Batangas, Philippines",
  },
  "ENGR_ELGINE_MANGCUPANG": {
    id: "ENGR_ELGINE_MANGCUPANG",
    name: "Engr. Elgine Mangcupang",
    nickname: "Engr. Elgine",
    role: "QA/QC Engineering Head",
    department: "QA_QC",
    skinTone: "LIGHT",
    gender: "FEMALE",
    hardhatColor: "#FFFFFF",
    vestColor: "#EA580C",
    hairStyle: "PONYTAIL",
    facialHair: "NONE",
    hasGlasses: true,
    avatarUrl: "/images/personnel/engr_maria_reyes.jpg",
    licenseNumber: "PRC Registered Civil / Materials QA/QC Engineer #0091834",
    currentTask: "Directing non-destructive testing (NDT), concrete compressive batch validation & electro-mechanical QA/QC inspection",
    locationName: "Site QA/QC Materials Testing Laboratory & Technical Office",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 12,
    originProvince: "Mindoro, Philippines",
  },
  "QC_JAIRUZ_BATAC": {
    id: "QC_JAIRUZ_BATAC",
    name: "Engr. Jairuz O. Batac",
    nickname: "Engr. Jairuz",
    role: "QC Engineer II - Tunnel & Geotechnical",
    department: "QA_QC",
    skinTone: "MEDIUM",
    gender: "MALE",
    hardhatColor: "#FFFFFF",
    vestColor: "#EA580C",
    hairStyle: "SHORT",
    facialHair: "NONE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/civil_jaime_cano.jpg",
    licenseNumber: "PRC Registered Civil Engineer #0087431",
    currentTask: "Conducting tunnel convergence rock bolt pull-out tests, shotcrete thickness verification & geotechnical QA/QC",
    locationName: "Headrace Tunnel Portal & Underground Quality Lab",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 8,
    originProvince: "Bulacan, Philippines",
  },
  "QC_JIMMY_AQUINO": {
    id: "QC_JIMMY_AQUINO",
    name: "Engr. Jimmy M. Aquino",
    nickname: "Engr. Jimmy",
    role: "QC Engineer - Civil Structures",
    department: "QA_QC",
    skinTone: "MEDIUM",
    gender: "MALE",
    hardhatColor: "#FFFFFF",
    vestColor: "#EA580C",
    hairStyle: "SHORT",
    facialHair: "NONE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/qc_jimmy_aquino.jpg",
    licenseNumber: "PRC Registered Civil Engineer #0079204",
    currentTask: "Performing pre-pour reinforcement inspections, slump testing & rebound hammer non-destructive testing",
    locationName: "Dam Spillway & Powerhouse Civil Structures Inspection Zone",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 11,
    originProvince: "Samar, Philippines",
  },
  "QC_JHON_JAYME": {
    id: "QC_JHON_JAYME",
    name: "Jhon Charles C. Jayme",
    nickname: "Engr. Charles",
    role: "Jr. QA/QC Engineer",
    department: "QA_QC",
    skinTone: "LIGHT",
    gender: "MALE",
    hardhatColor: "#FFFFFF",
    vestColor: "#EA580C",
    hairStyle: "SHORT",
    facialHair: "NONE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/planning_may_parallag.jpg",
    licenseNumber: "PRC Civil Engineer Licensure Candidate • QA/QC Inspector",
    currentTask: "Assisting QA/QC material sampling, concrete cylinder curing bath tests & field inspection logging",
    locationName: "Site QA/QC Field Testing Facility & Batch Plant",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 4,
    originProvince: "Caloocan, Philippines",
  },
  "PLANNING_MAY_PARALLAG": {
    id: "PLANNING_MAY_PARALLAG",
    name: "Engr. May Ann A. Parallag",
    nickname: "Engr. May Ann",
    role: "Jr. Planning Engineer",
    department: "ENGINEERING",
    skinTone: "LIGHT",
    gender: "FEMALE",
    hardhatColor: "#FFFFFF",
    vestColor: "#EA580C",
    hairStyle: "SHORT",
    facialHair: "NONE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/planning_may_parallag.jpg",
    licenseNumber: "PRC Civil Engineer #0098421 • Primavera P6 Specialist",
    currentTask: "Updating baseline Gantt schedules, critical path delay analysis & weekly S-curve generation",
    locationName: "Project Planning & Scheduling Technical Office",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 6,
    originProvince: "Isabela, Philippines",
  },
  "QS_CRISTINE_ALMAZAN": {
    id: "QS_CRISTINE_ALMAZAN",
    name: "Cristine Joy Almazan",
    nickname: "Ma'am Cristine",
    role: "Quantity Surveyor",
    department: "ENGINEERING",
    skinTone: "LIGHT",
    gender: "FEMALE",
    hardhatColor: "#FFFFFF",
    vestColor: "#EA580C",
    hairStyle: "PONYTAIL",
    facialHair: "NONE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/qs_cristine_almazan.jpg",
    licenseNumber: "PICQS Registered Quantity Surveyor / Cost Engineer",
    currentTask: "Preparing monthly progress billings, take-off evaluations & subcontractor claims verification",
    locationName: "Engineering Commercial & Cost Control Office",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 9,
    originProvince: "Tarlac, Philippines",
  },
  "SURVEYOR_JOHNNY_FARONGEY": {
    id: "SURVEYOR_JOHNNY_FARONGEY",
    name: "Johnny P. Farong-ey",
    nickname: "Chief Johnny",
    role: "Surveyor III (Lead Geodetic Surveyor)",
    department: "ENGINEERING",
    skinTone: "BRONZE",
    gender: "MALE",
    hardhatColor: "#EAB308",
    vestColor: "#EA580C",
    hairStyle: "SHORT",
    facialHair: "NONE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/surveyor_johnny_farongey.jpg",
    licenseNumber: "PRC Registered Geodetic Engineer #0062910",
    currentTask: "Executing precision GPS benchmark control, penstock axis layout & dam crest deformation monitoring",
    locationName: "Field Geodetic Survey Base & Topographical Command Office",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 15,
    originProvince: "Baguio, Philippines",
  },
  "GEO_AMOR_FLORESCA": {
    id: "GEO_AMOR_FLORESCA",
    name: "Amor Teofilo N. Floresca Jr.",
    nickname: "Sir Amor",
    role: "Geological Mapper & Engineering Geologist",
    department: "ENGINEERING",
    skinTone: "MEDIUM",
    gender: "MALE",
    hardhatColor: "#FFFFFF",
    vestColor: "#EA580C",
    hairStyle: "SHORT",
    facialHair: "NONE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/geo_amor_floresca_real.jpg",
    licenseNumber: "PRC Registered Geologist #0004289",
    currentTask: "Conducting tunnel face 3D geological mapping, Rock Mass Rating (RMR/Q-system) logging & overbreak monitoring",
    locationName: "Headrace Tunnel Face & Underground Geological Base",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 11,
    originProvince: "Baguio, Philippines",
  },
  "DOC_JAYSON_AGGABAO": {
    id: "DOC_JAYSON_AGGABAO",
    name: "Jayson Z. Aggabao",
    nickname: "Sir Jayson",
    role: "Document Controller",
    department: "ENGINEERING",
    skinTone: "MEDIUM",
    gender: "MALE",
    hardhatColor: "#FFFFFF",
    vestColor: "#0284C7",
    hairStyle: "SHORT",
    facialHair: "STUBBLE",
    hasGlasses: true,
    avatarUrl: "/images/personnel/doc_jayson_aggabao_real.png",
    licenseNumber: "ISO 9001:2015 Quality Management Document Control Specialist",
    currentTask: "Archiving approved submittals, transmittals, RFI logs & managing project drawing register",
    locationName: "Main Technical & Project Engineering Office (Document Control)",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 10,
    originProvince: "Isabela, Philippines",
  },
  "CAD_ELBERT_FIGURACION": {
    id: "CAD_ELBERT_FIGURACION",
    name: "Elbert Figuracion",
    nickname: "Sir Elbert",
    role: "AutoCAD Operator",
    department: "ENGINEERING",
    skinTone: "MEDIUM",
    gender: "MALE",
    hardhatColor: "#FFFFFF",
    vestColor: "#EA580C",
    hairStyle: "SHORT",
    facialHair: "NONE",
    hasGlasses: true,
    avatarUrl: "/images/personnel/cad_elbert_figuracion_real.jpg",
    licenseNumber: "Autodesk Certified Professional (ACP) • CADD & Civil 3D Specialist",
    currentTask: "Drafting structural as-built revisions, penstock alignment detailing & updating civil CAD drawing submittals",
    locationName: "Main Technical & Project Engineering Office (CADD Workstation)",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 12,
    originProvince: "Laguna, Philippines",
  },

  // ─── 3. CIVIL WORKS & SITE SUPERVISION ───
  "CIVIL_JAIME_CANO": {
    id: "CIVIL_JAIME_CANO",
    name: "Jaime B. Caño Jr.",
    nickname: "Foreman Caño",
    role: "Supervisor III - Civil Works",
    department: "CIVIL",
    skinTone: "BRONZE",
    gender: "MALE",
    hardhatColor: "#16A34A",
    vestColor: "#EA580C",
    hairStyle: "SHORT",
    facialHair: "NONE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/civil_jaime_cano.jpg",
    licenseNumber: "PRC Civil Engineering Practitioner / Master Construction Supervisor",
    currentTask: "Supervising heavy concrete pouring, tunnel excavation & civil structures alignment",
    locationName: "Upper Cascade Dam & Powerhouse Civil Works Area",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 17,
    originProvince: "Cagayan Valley, Philippines",
  },
  "CIVIL_HENRY_ESTRADA": {
    id: "CIVIL_HENRY_ESTRADA",
    name: "Henry V. Estrada",
    nickname: "Sir Henry",
    role: "Supervisor III - Civil Works & 4S",
    department: "CIVIL",
    skinTone: "BRONZE",
    gender: "MALE",
    hardhatColor: "#16A34A",
    vestColor: "#EA580C",
    hairStyle: "SHORT",
    facialHair: "MUSTACHE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/civil_jaime_cano.jpg",
    licenseNumber: "PRC Civil Engineering Specialist / Master Concrete Pouring Supervisor",
    currentTask: "Managing dam spillway batching, formwork structural integrity & civil 4S safety compliance",
    locationName: "Dam Spillway Concrete Staging & Tailrace Civil Works",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 18,
    originProvince: "Pangasinan, Philippines",
  },
  "TUNNEL_RICHARD_PINASEN": {
    id: "TUNNEL_RICHARD_PINASEN",
    name: "Richard A. Pinasen",
    nickname: "Foreman Richard",
    role: "Foreman III - Head Tunneling & Underground Works",
    department: "CIVIL",
    skinTone: "DEEP",
    gender: "MALE",
    hardhatColor: "#16A34A",
    vestColor: "#EA580C",
    hairStyle: "SHORT",
    facialHair: "NONE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/civil_jaime_cano.jpg",
    licenseNumber: "TESDA Certified Underground Drilling & Tunneling Specialist NC-III",
    currentTask: "Directing headrace tunnel drill-and-blast advance, shotcrete rock support & steel rib installation",
    locationName: "Headrace Tunnel Intake & Underground Penstock Section",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 15,
    originProvince: "Benguet (Cordillera), Philippines",
  },
  "TUNNEL_RUDY_MARCOS": {
    id: "TUNNEL_RUDY_MARCOS",
    name: "Rudy C. Marcos",
    nickname: "Foreman Rudy",
    role: "Foreman III - Underground Tunneling Excavation",
    department: "CIVIL",
    skinTone: "BRONZE",
    gender: "MALE",
    hardhatColor: "#16A34A",
    vestColor: "#EA580C",
    hairStyle: "SHORT",
    facialHair: "MUSTACHE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/civil_jaime_cano.jpg",
    licenseNumber: "TESDA Master Tunneling & Underground Blasting Specialist NC-III",
    currentTask: "Directing daily mucking cycles, ventilation line extensions & tunnel lining steel set erection",
    locationName: "Headrace Tunnel Underground Drive & Adit Portal",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 16,
    originProvince: "Benguet, Philippines",
  },
  "FOREMAN_ANTHONY_ROSALES": {
    id: "FOREMAN_ANTHONY_ROSALES",
    name: "Anthony B. Rosales",
    nickname: "Foreman Anthony",
    role: "Foreman III - Civil Structures",
    department: "CIVIL",
    skinTone: "MEDIUM",
    gender: "MALE",
    hardhatColor: "#16A34A",
    vestColor: "#EA580C",
    hairStyle: "SHORT",
    facialHair: "NONE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/civil_jaime_cano.jpg",
    licenseNumber: "TESDA Structural Formwork & Heavy Concreting NC-II",
    currentTask: "Coordinating powerhouse substructure concrete form setting and anchor bolt placement",
    locationName: "Powerhouse Substructure & Penstock Anchor Block #3",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 14,
    originProvince: "Batangas, Philippines",
  },
  "WORKER_BENJAMIN_FOMEGAS": {
    id: "WORKER_BENJAMIN_FOMEGAS",
    name: "Benjamin C. Fomeg-as",
    nickname: "Benjo",
    role: "Tunnel Worker III (Lead Jumbo Drill & Rock Support Specialist)",
    department: "CIVIL",
    skinTone: "DEEP",
    gender: "MALE",
    hardhatColor: "#16A34A",
    vestColor: "#EA580C",
    hairStyle: "SHORT",
    facialHair: "STUBBLE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/civil_jaime_cano.jpg",
    licenseNumber: "TESDA Underground Mining & Hydraulic Jumbo Drill Operator NC-II",
    currentTask: "Operating twin-boom hydraulic jumbo drill rig for blast holes, rock bolt setting & wire mesh installation",
    locationName: "Headrace Tunnel Heading & Underground Excavation Portal",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 13,
    originProvince: "Mountain Province (Cordillera), Philippines",
  },

  // ─── 4. SAFETY, HEALTH & ENVIRONMENT (ESH) ───
  "ESH_ALFREDO_ARIZ": {
    id: "ESH_ALFREDO_ARIZ",
    name: "Alfredo T. Ariz",
    nickname: "Sir Ariz",
    role: "Environmental, Safety & Health (ESH) Head",
    department: "SAFETY",
    skinTone: "BRONZE",
    gender: "MALE",
    hardhatColor: "#FFFFFF",
    vestColor: "#EAB308",
    hairStyle: "SHORT",
    facialHair: "MUSTACHE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/esh_alfredo_ariz.jpg",
    licenseNumber: "DOLE-OSHC Certified Safety Officer 4 (SO4) #38102 • ECC Environmental Manager",
    currentTask: "Directing site-wide safety compliance, emergency response protocols & environmental mitigation",
    locationName: "ESH Command & Safety Operations Center (TEMFACIL Compound)",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 18,
    originProvince: "Apayao, Philippines",
  },
  "NURSE_RUSSELLE_ALCANTARA": {
    id: "NURSE_RUSSELLE_ALCANTARA",
    name: "Russelle P. Alcantara, RN",
    nickname: "Nurse Russelle",
    role: "Project Nurse",
    department: "MEDICAL",
    skinTone: "MEDIUM",
    gender: "FEMALE",
    hardhatColor: "#FFFFFF",
    vestColor: "#DC2626",
    hairStyle: "PONYTAIL",
    facialHair: "NONE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/nurse_russelle_alcantara.jpg",
    licenseNumber: "PRC Registered Nurse #0074192 • DOLE BOSH Medical Practitioner",
    currentTask: "Conducting daily worker health screenings, emergency first-aid care & administering site clinic",
    locationName: "TEMFACIL Site Medical Clinic & Emergency First Aid Station",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 10,
    originProvince: "Isabela, Philippines",
  },
  "SEC_RONALD_MALTO": {
    id: "SEC_RONALD_MALTO",
    name: "Ronald D. Malto",
    nickname: "Officer Ronald",
    role: "Security Officer",
    department: "SAFETY",
    skinTone: "BRONZE",
    gender: "MALE",
    hardhatColor: "#FFFFFF",
    vestColor: "#1E293B",
    hairStyle: "SHORT",
    facialHair: "NONE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/esh_alfredo_ariz.jpg",
    licenseNumber: "PNP-SOSIA Licensed Security Practitioner #SO-2019-11204",
    currentTask: "Patrolling project perimeter, monitoring compound surveillance cameras & access logs",
    locationName: "Main TEMFACIL Security Gate & Perimeter Guardpost",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 12,
    originProvince: "Pangasinan, Philippines",
  },

  // ─── 5. ADMINISTRATION, HR & IT SYSTEMS ───
  "HR_ROVIGAIL_ABELLAR": {
    id: "HR_ROVIGAIL_ABELLAR",
    name: "Rovigail Joy G. Abellar",
    nickname: "Ma'am Rovi",
    role: "HR Officer & Timekeeper Lead",
    department: "ADMIN_HR",
    skinTone: "LIGHT",
    gender: "FEMALE",
    hardhatColor: "#FFFFFF",
    vestColor: "#0284C7",
    hairStyle: "PONYTAIL",
    facialHair: "NONE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/hr_rovigail_abellar.jpg",
    licenseNumber: "CHRP Certified Human Resources Professional",
    currentTask: "Managing daily site attendance logs, manpower timekeeping & employee relations across project",
    locationName: "Main TEMFACIL HR & Administration Office",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 8,
    originProvince: "Isabela, Philippines",
  },
  "HR_JOSHUA_ADMIN": {
    id: "HR_JOSHUA_ADMIN",
    name: "Joshua",
    nickname: "Sir Josh",
    role: "HR Admin",
    department: "ADMIN_HR",
    skinTone: "LIGHT",
    gender: "MALE",
    hardhatColor: "#FFFFFF",
    vestColor: "#0284C7",
    hairStyle: "SHORT",
    facialHair: "NONE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/hr_joshua_admin.jpg",
    licenseNumber: "CHRP Certified Human Resources Administrator",
    currentTask: "Processing site personnel administrative records, onboarding documentation & staff deployment logistics",
    locationName: "Main TEMFACIL HR & Administration Office",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 6,
    originProvince: "Isabela, Philippines",
  },
  "HR_RANDY_GAMBOA": {
    id: "HR_RANDY_GAMBOA",
    name: "Randy Gamboa",
    nickname: "Sir Randy",
    role: "HR Assistant",
    department: "ADMIN_HR",
    skinTone: "MEDIUM",
    gender: "MALE",
    hardhatColor: "#FFFFFF",
    vestColor: "#0284C7",
    hairStyle: "SHORT",
    facialHair: "GOATEE",
    hasGlasses: true,
    avatarUrl: "/images/personnel/hr_randy_gamboa_real.jpg",
    licenseNumber: "HR Administrative & Manpower Records Specialist",
    currentTask: "Assisting daily manpower attendance verification, biometric log reconciliations & HR field coordination",
    locationName: "Main TEMFACIL HR & Administration Office",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 5,
    originProvince: "Isabela, Philippines",
  },
  "IT_MARC_SALVA": {
    id: "IT_MARC_SALVA",
    name: "Harrold Salva",
    nickname: "Harrold",
    role: "IT Support Specialist",
    department: "IT_SYSTEMS",
    skinTone: "LIGHT",
    gender: "MALE",
    hardhatColor: "#0284C7",
    vestColor: "#0284C7",
    hairStyle: "SHORT",
    facialHair: "NONE",
    hasGlasses: true,
    avatarUrl: "/images/personnel/it_marc_salva.jpg",
    licenseNumber: "CompTIA Network+ / Cisco CCNA / Systems Infrastructure Specialist",
    currentTask: "Managing site Starlink telemetry links, local server racks, SCADA network relays & IT workstations",
    locationName: "IT Operations & Telemetry Server Room (Main TEMFACIL)",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 7,
    originProvince: "Isabela, Philippines",
  },

  // ─── 6. LOGISTICS, WAREHOUSE & FLEET ───
  "EQUIP_HOWELL_SAMSON": {
    id: "EQUIP_HOWELL_SAMSON",
    name: "Howell Gene E. Samson",
    nickname: "Sir Howell",
    role: "Supervisor - Heavy Equipment & Fleet",
    department: "LOGISTICS",
    skinTone: "MEDIUM",
    gender: "MALE",
    hardhatColor: "#EAB308",
    vestColor: "#EA580C",
    hairStyle: "SHORT",
    facialHair: "NONE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/equip_howell_samson.jpg",
    licenseNumber: "TESDA Heavy Equipment Maintenance Assessor NC-III",
    currentTask: "Directing preventive maintenance schedules, fuel logistics & equipment deployment across project",
    locationName: "Central Motorpool, Heavy Equipment Staging Yard & Fuel Depot",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 16,
    originProvince: "Pampanga, Philippines",
  },
  "WAREHOUSE_VINCENT_ANDALLO": {
    id: "WAREHOUSE_VINCENT_ANDALLO",
    name: "Vincent Dickenson Andallo",
    nickname: "Sir Vincent",
    role: "Warehouse Area Lead",
    department: "LOGISTICS",
    skinTone: "BRONZE",
    gender: "MALE",
    hardhatColor: "#0284C7",
    vestColor: "#EAB308",
    hairStyle: "SHORT",
    facialHair: "GOATEE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/warehouse_vincent_andallo.jpg",
    licenseNumber: "Certified Supply Chain & Materials Inventory Specialist",
    currentTask: "Overseeing bulk cement shipments, rebar deliveries, spare parts inventory & warehouse issuance",
    locationName: "Central Warehouse, Rebar Staging Yard & Material Storage Compound",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 14,
    originProvince: "Isabela, Philippines",
  },

  // ─── 7. MECHANICAL & ELECTRICAL WORKS ───
  "SUPT_EUGENIO_HANOPOL": {
    id: "SUPT_EUGENIO_HANOPOL",
    name: "Eugenio D. Hanopol",
    nickname: "Supt. Eugene",
    role: "Superintendent I - Mechanical",
    department: "ELECTRICAL",
    skinTone: "MEDIUM",
    gender: "MALE",
    hardhatColor: "#FFFFFF",
    vestColor: "#EA580C",
    hairStyle: "SHORT",
    facialHair: "MUSTACHE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/mech_eugenio_hanopol.jpg",
    licenseNumber: "PRC Professional Mechanical Engineer #0029410",
    currentTask: "Overseeing powerhouse turbine runner assembly, penstock valve fitment & generator alignment",
    locationName: "Powerhouse Mechanical Floor & Turbine Bay (EL. 180.00m)",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 25,
    originProvince: "Pampanga, Philippines",
  },
  "SUPT_EDUARDO_DEFRANCIA": {
    id: "SUPT_EDUARDO_DEFRANCIA",
    name: "Eduardo G. De Francia",
    nickname: "Supt. Ed",
    role: "Electrical Superintendent",
    department: "ELECTRICAL",
    skinTone: "MEDIUM",
    gender: "MALE",
    hardhatColor: "#FFFFFF",
    vestColor: "#0284C7",
    hairStyle: "SHORT",
    facialHair: "MUSTACHE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/deputy_nathaniel_principe.jpg",
    licenseNumber: "PRC Registered Electrical Engineer #0044812 • Master Electrician",
    currentTask: "Directing 69kV switchyard construction, step-up transformer bay wiring & high-voltage relay testing",
    locationName: "69kV Switchyard & Powerhouse Electrical Control Room",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 23,
    originProvince: "Pangasinan, Philippines",
  },
  "ELEC_JOSUE_ABELLERA": {
    id: "ELEC_JOSUE_ABELLERA",
    name: "Josue A. Abellera",
    nickname: "Sir Josue",
    role: "Supervisor III - Electrical Works",
    department: "ELECTRICAL",
    skinTone: "BRONZE",
    gender: "MALE",
    hardhatColor: "#0284C7",
    vestColor: "#0284C7",
    hairStyle: "SHORT",
    facialHair: "NONE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/civil_jaime_cano.jpg",
    licenseNumber: "PRC Registered Electrical Practitioner #0065120",
    currentTask: "Supervising cable ladder installation, generator feeder conduits & powerhouse auxiliary power distribution",
    locationName: "Powerhouse Electrical Invert & Cable Vaults",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 16,
    originProvince: "La Union, Philippines",
  },
  "FOREMAN_WARLITO_DEFRANCIA": {
    id: "FOREMAN_WARLITO_DEFRANCIA",
    name: "Warlito D. De Francia",
    nickname: "Foreman Warlito",
    role: "Foreman I - Electrical",
    department: "ELECTRICAL",
    skinTone: "MEDIUM",
    gender: "MALE",
    hardhatColor: "#0284C7",
    vestColor: "#0284C7",
    hairStyle: "SHORT",
    facialHair: "NONE",
    hasGlasses: false,
    avatarUrl: "/images/personnel/civil_jaime_cano.jpg",
    licenseNumber: "TESDA Building Wiring & Electrical Installation NC-II",
    currentTask: "Leading electrical roughing-ins, switchgear busbar connections & grounding grid installations",
    locationName: "Powerhouse Electrical Gallery & Control Room",
    shift: "Day Shift (07:00 - 16:00)",
    yearsOfExp: 14,
    originProvince: "Pangasinan, Philippines",
  },
};
